apiVersion: batch/v1
kind: Job
metadata:
  name: pause-job
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
      - name: pause-container
        image: busybox
        command: ["sleep", "120"]
      restartPolicy: Never
  backoffLimit: 4